### ISSUE TITLE
Show month name instead of month number in Date Box

### ISSUE THREAD

**Issue by georges49** [jtsage/jtsage-datebox#421]
Hi, 
Is there a way to show the month name instead of month number in date box?
So I want it to be Jan, Feb instead of 1 2
I searched in the library documentation but I could not find it.

**Comment by jtsage** [comment]
Yep, but it's not obvious.

http://dev.jtsage.com/DateBox/api/dateFieldOrder/

basically, set overrideDateFieldOrder: ["M", "d", "y"]

(capital M instead of lower case. You could also do this in a i18n language file if you support more than one language and it doesn't make sense to change it for everybody)

**Comment by georges49** [comment]
Thanks a lot @jtsage . That worked the way I want it.
