### ISSUE TITLE
Upgrading to v5.1.0 jqm calUsePickers not showing years

### ISSUE THREAD

**Issue by gregh3269** [jtsage/jtsage-datebox#470]
Also for some reason the year picker does not show.  It pops but where the year should be there are - +  to advance, but the text between is empty and no month/year (not even a blank line).

This is what I am using:
`<input name="createdString" id="createdString${uuId}" type="text" value="${visitDateString}" data-role="datebox" data-options='{"mode": "calbox", "theme_headerTheme" : "b", "useFocus":true, "overrideDateFormat": "%d/%m/%y", "beforeToday" : "true", "calUsePickers": "true", "calYearPickMin" : -5, "calYearPickMax" : 0, "disabledState": "disabled", "displayDropdownPosition":"centerMiddle" }' readonly="readonly" data-inline="true" />`

**Comment by jtsage** [comment]
Heh. This one is stupid.  

It's because "true" !== true.  It's a json parsing thing.  If you wanted to test it on your end real quick without the quotes around "true" on the calUsePickers option, it'll verify.

But, I am going to flip the flag on that option, and any others just like it to only be off if they are absolutely false, and on otherwise.

**Comment by gregh3269** [comment]
Ah ok, that works, my typo.

**Comment by jtsage** [comment]
Yeah, it's my fault.  It's because in that specific instance I'm testing value and variable type - usually when I do that, I test against the default instead, which is what the commit in a minute will have.

In this specific case, the option has to be true, and be a boolean.  When I push in a second, to turn it on, the option needs to not be the boolean false.  As it default to boolean false, this makes way more sense in context.

**Comment by gregh3269** [comment]
I will convert/test some more and log new issues if needed.

Thanks

**Comment by jtsage** [comment]
Thank you.  Very much.  

This project was originally built for a specific purpose, which at the time was built on top of jQM.  Since then, the scope of that project has changed a bit (making most of what DateBox can do unnecessary), and it's built on top of bootstrap now.  At any rate, I don't spend nearly the time testing on jQM as I should.  So, thanks again for not only using this, but also reporting back the issues as you find them.

**Comment by gregh3269** [comment]
Ah, the trouble with frameworks, they suck you in then all the talent leaves.

**Comment by jtsage** [comment]
Fix pushed to release, SHA: 366e8c237edd874964ed1f717df8abb2a8a1a3ee (5.1.2)

Closing issue, if this comes back, or I missed something, feel free to re-open.
